// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MType int32

const (
	Metric_COUNTER Metric_MType = 0
	Metric_GAUGE   Metric_MType = 1
)

// Enum value maps for Metric_MType.
var (
	Metric_MType_name = map[int32]string{
		0: "COUNTER",
		1: "GAUGE",
	}
	Metric_MType_value = map[string]int32{
		"COUNTER": 0,
		"GAUGE":   1,
	}
)

func (x Metric_MType) Enum() *Metric_MType {
	p := new(Metric_MType)
	*p = x
	return p
}

func (x Metric_MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (Metric_MType) Type() protoreflect.EnumType {
	return &file_proto_metrics_proto_enumTypes[0]
}

func (x Metric_MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MType.Descriptor instead.
func (Metric_MType) EnumDescriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0, 0}
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype Metric_MType           `protobuf:"varint,2,opt,name=mtype,proto3,enum=github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric_MType" json:"mtype,omitempty"`
	// Types that are valid to be assigned to MetricValue:
	//
	//	*Metric_Delta
	//	*Metric_Value
	MetricValue   isMetric_MetricValue `protobuf_oneof:"metricValue"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMtype() Metric_MType {
	if x != nil {
		return x.Mtype
	}
	return Metric_COUNTER
}

func (x *Metric) GetMetricValue() isMetric_MetricValue {
	if x != nil {
		return x.MetricValue
	}
	return nil
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		if x, ok := x.MetricValue.(*Metric_Delta); ok {
			return x.Delta
		}
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		if x, ok := x.MetricValue.(*Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

type isMetric_MetricValue interface {
	isMetric_MetricValue()
}

type Metric_Delta struct {
	Delta int64 `protobuf:"varint,3,opt,name=delta,proto3,oneof"`
}

type Metric_Value struct {
	Value float64 `protobuf:"fixed64,4,opt,name=value,proto3,oneof"`
}

func (*Metric_Delta) isMetric_MetricValue() {}

func (*Metric_Value) isMetric_MetricValue() {}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x129github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto\"\xd7\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12]\n" +
	"\x05mtype\x18\x02 \x01(\x0e2G.github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric.MTypeR\x05mtype\x12\x16\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x12\x16\n" +
	"\x05value\x18\x04 \x01(\x01H\x00R\x05value\"\x1f\n" +
	"\x05MType\x12\v\n" +
	"\aCOUNTER\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01B\r\n" +
	"\vmetricValue\"m\n" +
	"\x0eMetricsRequest\x12[\n" +
	"\ametrics\x18\x01 \x03(\v2A.github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricR\ametrics\"'\n" +
	"\x0fMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xb2\x01\n" +
	"\aMetrics\x12\xa6\x01\n" +
	"\vSendMetrics\x12I.github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsRequest\x1aJ.github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsResponse(\x01B\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_metrics_proto_goTypes = []any{
	(Metric_MType)(0),       // 0: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric.MType
	(*Metric)(nil),          // 1: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric
	(*MetricsRequest)(nil),  // 2: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsRequest
	(*MetricsResponse)(nil), // 3: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsResponse
}
var file_proto_metrics_proto_depIdxs = []int32{
	0, // 0: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric.mtype:type_name -> github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric.MType
	1, // 1: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsRequest.metrics:type_name -> github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metric
	2, // 2: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metrics.SendMetrics:input_type -> github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsRequest
	3, // 3: github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.Metrics.SendMetrics:output_type -> github.com.Tanya1515.metrics_collector.git.cmd.grpc.proto.MetricsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	file_proto_metrics_proto_msgTypes[0].OneofWrappers = []any{
		(*Metric_Delta)(nil),
		(*Metric_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		EnumInfos:         file_proto_metrics_proto_enumTypes,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
